# What's the name of the church?
title: Camp Rhino Christmas Camp
# Give a brief description of the church
description: > # this means to ignore newlines until "baseurl:"
    Sponsor a child to go to Christian Summer Camp this Christmas Season.
# Leave this alone
baseurl: "" # the subpath of your site, e.g. /blog
# Change this to the domain when you are finished and ready to publish.

url: "http://christmascamp.org/" # the base hostname & protocol for your site | Switch to http://cranesvillebiblechurch.com/" Before running Glynn.  Afterwards change it back to http://localhost:4000/



# Airtable API Stuff
airtable:
  apikey: "keyRTLlrVS02vC3Vx"
  comingsoon: "appDwbqtNDcijVUDN"
  

# LEAVE EVERYTHING ELSE ALONE!!

# Build settings
markdown: kramdown
 
# Exclude
exclude:
  - package.json
  - node_modules
  - gulpfile.js 
  - bower_components
keep_files:
  - css
  - assets/css
  - assets/js 


ftp_host: 'biblebaptistmattoon.org'
ftp_dir: 'christmascamp.org/'
ftp_passive: false
ftp_username: 'ryahay11'
ftp_password: '@88Volvocj'
